# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import analytics_pb2 as analytics__pb2

GRPC_GENERATED_VERSION = '1.81.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in analytics_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AnalyticsServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetAnalyticsSummary = channel.unary_unary(
                '/analytics.v1.AnalyticsService/GetAnalyticsSummary',
                request_serializer=analytics__pb2.SummaryRequest.SerializeToString,
                response_deserializer=analytics__pb2.SummaryResponse.FromString,
                _registered_method=True)
        self.GetTrends = channel.unary_unary(
                '/analytics.v1.AnalyticsService/GetTrends',
                request_serializer=analytics__pb2.TrendsRequest.SerializeToString,
                response_deserializer=analytics__pb2.TrendsResponse.FromString,
                _registered_method=True)
        self.GetCurrentMetrics = channel.unary_unary(
                '/analytics.v1.AnalyticsService/GetCurrentMetrics',
                request_serializer=analytics__pb2.MetricsRequest.SerializeToString,
                response_deserializer=analytics__pb2.MetricsResponse.FromString,
                _registered_method=True)


class AnalyticsServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def GetAnalyticsSummary(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTrends(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCurrentMetrics(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AnalyticsServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetAnalyticsSummary': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAnalyticsSummary,
                    request_deserializer=analytics__pb2.SummaryRequest.FromString,
                    response_serializer=analytics__pb2.SummaryResponse.SerializeToString,
            ),
            'GetTrends': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTrends,
                    request_deserializer=analytics__pb2.TrendsRequest.FromString,
                    response_serializer=analytics__pb2.TrendsResponse.SerializeToString,
            ),
            'GetCurrentMetrics': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCurrentMetrics,
                    request_deserializer=analytics__pb2.MetricsRequest.FromString,
                    response_serializer=analytics__pb2.MetricsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'analytics.v1.AnalyticsService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('analytics.v1.AnalyticsService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AnalyticsService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetAnalyticsSummary(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/analytics.v1.AnalyticsService/GetAnalyticsSummary',
            analytics__pb2.SummaryRequest.SerializeToString,
            analytics__pb2.SummaryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetTrends(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/analytics.v1.AnalyticsService/GetTrends',
            analytics__pb2.TrendsRequest.SerializeToString,
            analytics__pb2.TrendsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetCurrentMetrics(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/analytics.v1.AnalyticsService/GetCurrentMetrics',
            analytics__pb2.MetricsRequest.SerializeToString,
            analytics__pb2.MetricsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
