# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: analytics.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'analytics.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0f\x61nalytics.proto\x12\x0c\x61nalytics.v1\"D\n\x0eSummaryRequest\x12\x0e\n\x06org_id\x18\x01 \x01(\t\x12\x11\n\tfrom_date\x18\x02 \x01(\t\x12\x0f\n\x07to_date\x18\x03 \x01(\t\"\x82\x01\n\x0fSummaryResponse\x12\x16\n\x0etotal_mentions\x18\x01 \x01(\x03\x12\x14\n\x0cpositive_pct\x18\x02 \x01(\x02\x12\x14\n\x0cnegative_pct\x18\x03 \x01(\x02\x12\x13\n\x0b\x61vg_per_day\x18\x04 \x01(\x02\x12\x16\n\x0espike_detected\x18\x05 \x01(\x08\"G\n\rTrendsRequest\x12\x0e\n\x06org_id\x18\x01 \x01(\t\x12\x13\n\x0bgranularity\x18\x02 \x01(\t\x12\x11\n\tfrom_date\x18\x03 \x01(\t\"^\n\nTrendPoint\x12\x0c\n\x04time\x18\x01 \x01(\t\x12\r\n\x05\x63ount\x18\x02 \x01(\x03\x12\x10\n\x08positive\x18\x03 \x01(\x03\x12\x10\n\x08negative\x18\x04 \x01(\x03\x12\x0f\n\x07neutral\x18\x05 \x01(\x03\">\n\x0eTrendsResponse\x12,\n\ndatapoints\x18\x01 \x03(\x0b\x32\x18.analytics.v1.TrendPoint\" \n\x0eMetricsRequest\x12\x0e\n\x06org_id\x18\x01 \x01(\t\"j\n\x0fMetricsResponse\x12\x16\n\x0etotal_mentions\x18\x01 \x01(\x03\x12\x14\n\x0cpositive_pct\x18\x02 \x01(\x02\x12\x14\n\x0cnegative_pct\x18\x03 \x01(\x02\x12\x13\n\x0bspike_count\x18\x04 \x01(\x03\x32\x80\x02\n\x10\x41nalyticsService\x12R\n\x13GetAnalyticsSummary\x12\x1c.analytics.v1.SummaryRequest\x1a\x1d.analytics.v1.SummaryResponse\x12\x46\n\tGetTrends\x12\x1b.analytics.v1.TrendsRequest\x1a\x1c.analytics.v1.TrendsResponse\x12P\n\x11GetCurrentMetrics\x12\x1c.analytics.v1.MetricsRequest\x1a\x1d.analytics.v1.MetricsResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'analytics_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SUMMARYREQUEST']._serialized_start=33
  _globals['_SUMMARYREQUEST']._serialized_end=101
  _globals['_SUMMARYRESPONSE']._serialized_start=104
  _globals['_SUMMARYRESPONSE']._serialized_end=234
  _globals['_TRENDSREQUEST']._serialized_start=236
  _globals['_TRENDSREQUEST']._serialized_end=307
  _globals['_TRENDPOINT']._serialized_start=309
  _globals['_TRENDPOINT']._serialized_end=403
  _globals['_TRENDSRESPONSE']._serialized_start=405
  _globals['_TRENDSRESPONSE']._serialized_end=467
  _globals['_METRICSREQUEST']._serialized_start=469
  _globals['_METRICSREQUEST']._serialized_end=501
  _globals['_METRICSRESPONSE']._serialized_start=503
  _globals['_METRICSRESPONSE']._serialized_end=609
  _globals['_ANALYTICSSERVICE']._serialized_start=612
  _globals['_ANALYTICSSERVICE']._serialized_end=868
# @@protoc_insertion_point(module_scope)
