# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: nlp.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'nlp.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tnlp.proto\x12\x06nlp.v1\"&\n\x15SentimentBatchRequest\x12\r\n\x05texts\x18\x01 \x03(\t\"J\n\x0fSentimentResult\x12\x11\n\tsentiment\x18\x01 \x01(\t\x12\x12\n\nconfidence\x18\x02 \x01(\x02\x12\x10\n\x08keywords\x18\x03 \x03(\t\"B\n\x16SentimentBatchResponse\x12(\n\x07results\x18\x01 \x03(\x0b\x32\x17.nlp.v1.SentimentResult\"\x1f\n\x0f\x45ntitiesRequest\x12\x0c\n\x04text\x18\x01 \x01(\t\"4\n\x06\x45ntity\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\r\n\x05label\x18\x02 \x01(\t\x12\r\n\x05score\x18\x03 \x01(\x02\"4\n\x10\x45ntitiesResponse\x12 \n\x08\x65ntities\x18\x01 \x03(\x0b\x32\x0e.nlp.v1.Entity2\xac\x01\n\nNlpService\x12R\n\x11GetSentimentBatch\x12\x1d.nlp.v1.SentimentBatchRequest\x1a\x1e.nlp.v1.SentimentBatchResponse\x12J\n\x15GetEntitiesForMention\x12\x17.nlp.v1.EntitiesRequest\x1a\x18.nlp.v1.EntitiesResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'nlp_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SENTIMENTBATCHREQUEST']._serialized_start=21
  _globals['_SENTIMENTBATCHREQUEST']._serialized_end=59
  _globals['_SENTIMENTRESULT']._serialized_start=61
  _globals['_SENTIMENTRESULT']._serialized_end=135
  _globals['_SENTIMENTBATCHRESPONSE']._serialized_start=137
  _globals['_SENTIMENTBATCHRESPONSE']._serialized_end=203
  _globals['_ENTITIESREQUEST']._serialized_start=205
  _globals['_ENTITIESREQUEST']._serialized_end=236
  _globals['_ENTITY']._serialized_start=238
  _globals['_ENTITY']._serialized_end=290
  _globals['_ENTITIESRESPONSE']._serialized_start=292
  _globals['_ENTITIESRESPONSE']._serialized_end=344
  _globals['_NLPSERVICE']._serialized_start=347
  _globals['_NLPSERVICE']._serialized_end=519
# @@protoc_insertion_point(module_scope)
