# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import nlp_pb2 as nlp__pb2

GRPC_GENERATED_VERSION = '1.81.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in nlp_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class NlpServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetSentimentBatch = channel.unary_unary(
                '/nlp.v1.NlpService/GetSentimentBatch',
                request_serializer=nlp__pb2.SentimentBatchRequest.SerializeToString,
                response_deserializer=nlp__pb2.SentimentBatchResponse.FromString,
                _registered_method=True)
        self.GetEntitiesForMention = channel.unary_unary(
                '/nlp.v1.NlpService/GetEntitiesForMention',
                request_serializer=nlp__pb2.EntitiesRequest.SerializeToString,
                response_deserializer=nlp__pb2.EntitiesResponse.FromString,
                _registered_method=True)


class NlpServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def GetSentimentBatch(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetEntitiesForMention(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_NlpServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetSentimentBatch': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSentimentBatch,
                    request_deserializer=nlp__pb2.SentimentBatchRequest.FromString,
                    response_serializer=nlp__pb2.SentimentBatchResponse.SerializeToString,
            ),
            'GetEntitiesForMention': grpc.unary_unary_rpc_method_handler(
                    servicer.GetEntitiesForMention,
                    request_deserializer=nlp__pb2.EntitiesRequest.FromString,
                    response_serializer=nlp__pb2.EntitiesResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'nlp.v1.NlpService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('nlp.v1.NlpService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class NlpService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetSentimentBatch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/nlp.v1.NlpService/GetSentimentBatch',
            nlp__pb2.SentimentBatchRequest.SerializeToString,
            nlp__pb2.SentimentBatchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetEntitiesForMention(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/nlp.v1.NlpService/GetEntitiesForMention',
            nlp__pb2.EntitiesRequest.SerializeToString,
            nlp__pb2.EntitiesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
